project:
  type: website
  output-dir: _site

website:
  title: "kyleholdt.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
